### ISSUE TITLE
Practica 6 Infografía Hilos en Consola en C#

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/infografia-de-hilos-FedericoVictorianoSierra#2]
El estudiante  debe realizar el diseño de una infografía para plasmar características y aplicaciones de los hilos.
La infografía debe estar bien diseñada NO pirateada, debe tener una estructura adecuada.
La infografía debe responder a las siguientes preguntas.
¿Qué son los hilos?
¿Cuáles son sus características?
¿Cuáles son sus ventajas y desventajas?
¿En donde se aplican los hilos?
La infografía debe contener fuentes de información.

**Comment by FedericoVictorianoSierra** [comment]
[Practica 6 Infografía Hilos en Consola (Federico Victoriano Sierra(4US)).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-FedericoVictorianoSierra/files/8374534/Practica.6.Infografia.Hilos.en.Consola.Federico.Victoriano.Sierra.4US.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Practica 6 Infografía Hilos en Consola (Federico Victoriano Sierra(4US)).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-FedericoVictorianoSierra/files/8374683/Practica.6.Infografia.Hilos.en.Consola.Federico.Victoriano.Sierra.4US.pdf)

**Comment by JudithReynaCS** [comment]
Calificación:20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
